services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecomdb
    volumes:                                   # <-- MAGIC: Ye MySQL ke data ko bahar nikaal lega
      - mysql_data:/var/lib/mysql              # <-- /var/lib/mysql me MySQL asli data rakhta hai
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

# Sabse neeche locker (volume) ka naam declare karna zaroori hai
volumes:
  mysql_data:                                  # <-- Ye hamara permanent safe locker hai